### ISSUE TITLE
Version 1.4 in Maven Central is incompatible with live OMDB

### ISSUE THREAD

**Issue by GideonLeGrange** [Omertron/api-omdb#12]
Currently the version of api-omdb available in Maven Central is 1.4 and since OMDB API requires a key to work, we need to use 1.5. Building projects with a local clone of 1.5 is inconvenient. 

Can you please release 1.5 into Maven Central?

**Comment by Omertron** [comment]
This has been released to Maven, so give it a couple of hours to filter through
