### ISSUE TITLE
OmdbVideoFull to JSON

### ISSUE THREAD

**Issue by syfantid** [Omertron/api-omdb#5]
How can I convert the OmdbVideoFull object to JSON object?

**Comment by syfantid** [comment]
Used this approach: http://www.mkyong.com/java/how-do-convert-java-object-to-from-json-format-gson-api/

**Comment by Omertron** [comment]
Seeing as the project uses Jackson, rather than adding another library, you could just use that. The link is here: https://github.com/FasterXML/jackson

**Comment by syfantid** [comment]
Thanks! Didn't notice! ;)
