### ISSUE TITLE
Key

### ISSUE THREAD

**Issue by schvabodka-man** [Omertron/api-omdb#9]
It seems like they added key for omdb api. Would you please add it to your library?

**Comment by Omertron** [comment]
I will try and do this, but as I am not a subscriber to their patreon it may take a while.

**Comment by codemoth** [comment]
I forked and added the code for the api-key. Omertron you can merge back and release, I tried to keep it essentially the same with minimal changes.

**Comment by Omertron** [comment]
Sure, submit a pull request please and I'll merge it in

**Comment by Omertron** [comment]
closed with #10
